### ISSUE TITLE
Still not working on kde 5.27.3, pls can anyone fix it. please

### ISSUE THREAD

**Issue by Xeo23** [Zren/plasma-wallpapers#26]
I installed it from the git repo and it installed without any issue but i cant apply it in the wallpaper section.

**Comment by kneckergit** [comment]
If anyone is willing to fork (https://github.com/Zren/plasma-wallpapers) and make it work again, I will make a generous donation. Not having this plugin anymore is a disaster for my workflow...

**Comment by orychalk** [comment]
Hello,

It's a GREAT KDE effect 😃
Like Kneckergit, I can offer 10 € if anyone can uptate it to work on KDE 5.27.3 😊

Thanks

**Comment by kneckergit** [comment]
Up to 110 € now :) Anyone?

**Comment by bouteillerAlan** [comment]
Hello, I had a hard time to understand the errors (I'm a beginner on this framework and the doc is non-existent so ...) moreover since I don't know if this repo has vocation to continue to live, I made a new plugin for the blur effect using the same code as the default plugin "image" created by KDE. 

[check the repo here](https://github.com/bouteillerAlan/blurredwallpaper)

**Comment by orychalk** [comment]
Hello,
Thank you so much 😃
I installed it and it's work 😄

**Comment by Xeo23** [comment]
> Hello, I had a hard time to understand the errors (I'm a beginner on this framework and the doc is non-existent so ...) moreover since I don't know if this repo has vocation to continue to live, I made a new plugin for the blur effect using the same code as the default plugin "image" created by KDE.
> 
> [check the repo here](https://github.com/bouteillerAlan/blurredwallpaper)

You are a saviour man...❤️🙌🏻🫂
